'use strict';

const WebSocket = require('ws');
const NAMES = ['Brunex Nova','Brunex Orbit','Brunex Titan','Brunex Scout','Brunex Ghost','Brunex Ace','Brunex Guard','Brunex Bot'];
const rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;

function Bot(id){
 this.id=id;this.server='';this.origin='http://localhost';this.fixedDirection=null;this.shouldRandomize=false;this.isZigZag=false;this.botManager=null;this.cosmetic=11;this.tag=12;this.persistentBoost=false;this.mode='follow';this.targetX=null;this.targetY=null;
 this.tornadoSize=2000;this.tornadoSeparation=800;this.tornadoFinalAngle=90;this.tornadoRateOfChange=.5;this.tornadoRotationDir=1;this.tornadoActive=false;this.fixedCircleActive=false;this.fixedCircleX=null;this.fixedCircleY=null;this.fixedCircleSize=1712;this.fixedCircleFinalAngle=110;this.fixedCircleRateOfChange=.3;this.fixedCircleRotationDir=1;
 this.snakeID=null;this.snakeX=0;this.snakeY=0;this.snakeAngle=0;this.haveSnakeID=false;this.hasConnected=false;this.isBoost=false;this._reconnectTimer=null;this._movementTimer=null;this._pingTimer=null;this._manualDisconnect=false;
}
Bot.prototype.send=function(buf){if(this.ws&&this.ws.readyState===WebSocket.OPEN){try{this.ws.send(buf);}catch(_){}}};
Bot.prototype.connect=function(){if(this.ws&&(this.ws.readyState===WebSocket.OPEN||this.ws.readyState===WebSocket.CONNECTING))return;if(!this.server)return;this._manualDisconnect=false;const server=/^wss?:\/\//i.test(this.server)?this.server:`ws://${this.server}`;const options={headers:{Origin:this.origin||'http://localhost','User-Agent':'Mozilla/5.0'}};try{options.headers.Host=new URL(server).host;}catch(_){}this.server=server;this.ws=new WebSocket(server,options);this.ws.binaryType='nodebuffer';this.ws.on('message',d=>this.onMessage(d));this.ws.on('open',()=>this.onOpen());this.ws.on('close',()=>this.onClose());this.ws.on('error',e=>this.onError(e));};
Bot.prototype.setMode=function(m){this.mode=m||'follow';this.shouldRandomize=this.mode==='wander';this.tornadoActive=this.mode==='tornado';this.fixedCircleActive=this.mode==='spiral';if(this.mode==='spiral'&&this.botManager){this.fixedCircleX=this.botManager.xPos;this.fixedCircleY=this.botManager.yPos;}};
Bot.prototype.setTarget=function(x,y){const nx=Number(x),ny=Number(y);if(Number.isFinite(nx)&&Number.isFinite(ny)){this.targetX=nx;this.targetY=ny;}};
Bot.prototype.setRandomMovement=function(v){this.shouldRandomize=!!v;};Bot.prototype.setZigZagMovement=function(v){this.isZigZag=!!v;if(this.isZigZag)this.fixedDirection=null;};Bot.prototype.setTornadoMovement=function(v){this.tornadoActive=!!v;if(v){this.shouldRandomize=false;this.fixedCircleActive=false;}};
Bot.prototype.setTornadoSettings=function(s){s=s||{};this.tornadoSize=Number(s.size)||2000;this.tornadoSeparation=Number(s.separation)||800;this.tornadoFinalAngle=Number(s.finalAng)||90;this.tornadoRateOfChange=Number(s.rOC)||.5;this.tornadoRotationDir=Number(s.rotationDir)||1;};
Bot.prototype.setFixedCircleMovement=function(v){this.fixedCircleActive=!!v;if(v){this.shouldRandomize=false;this.tornadoActive=false;}};Bot.prototype.setFixedCircleSettings=function(s,x,y){s=s||{};this.fixedCircleSize=Number(s.size)||1712;this.fixedCircleFinalAngle=Number(s.finalAng)||110;this.fixedCircleRateOfChange=Number(s.rOC)||.3;this.fixedCircleRotationDir=Number(s.rotationDir)||1;this.fixedCircleX=x;this.fixedCircleY=y;};
Bot.prototype.spawn=function(){this.name=NAMES[rand(0,NAMES.length-1)];this.send(Buffer.from([115,12,1,8,66,114,117,110,101,120,89,84,0,255]));const t=this.botManager&&this.botManager.getMovementTarget();if(t&&t.x!=null&&t.y!=null)this.moveTo(t.x,t.y);};
Bot.prototype.moveTo=function(x,y){if(!Number.isFinite(Number(x))||!Number.isFinite(Number(y)))return;let tx=Number(x),ty=Number(y);if((this.mode==='headhunter'||this.mode==='focus')&&this.targetX!==null&&this.targetY!==null){tx=this.targetX;ty=this.targetY;}let angle;if(this.shouldRandomize)angle=[0,45,90,135,180,225][rand(0,5)]*Math.PI/125;else{const dx=tx-this.snakeX,dy=ty-this.snakeY,d=Math.hypot(dx,dy);angle=Math.atan2(dy,dx);if(this.tornadoActive&&d<=this.tornadoSize){const safe=Math.min(this.tornadoSeparation,this.tornadoSize-1),ratio=Math.max(0,Math.min(1,(d-safe)/Math.max(1,this.tornadoSize-safe))),bend=(this.tornadoFinalAngle*Math.PI/180)*(1-ratio)*this.tornadoRateOfChange;angle+=Math.PI/2+(this.tornadoRotationDir===0?-bend:bend);}else if(this.fixedCircleActive&&this.fixedCircleX!==null&&this.fixedCircleY!==null){const cx=this.fixedCircleX-this.snakeX,cy=this.fixedCircleY-this.snakeY,cd=Math.hypot(cx,cy);angle=Math.atan2(cy,cx);if(cd<=this.fixedCircleSize)angle+=(this.fixedCircleRotationDir===1?1:-1)*(this.fixedCircleFinalAngle*Math.PI/180)*(1-cd/this.fixedCircleSize)*this.fixedCircleRateOfChange;}else if(this.mode==='focus'&&d>0)angle+=(this.id%2?1:-1)*Math.min(.35,3000/d)*Math.PI/8;}while(angle<0)angle+=Math.PI*2;while(angle>=Math.PI*2)angle-=Math.PI*2;const value=Math.max(0,Math.min(250,Math.floor(angle*125/Math.PI)));this.snakeAngle=value;const buf=Buffer.from([value]);this.send(this.isBoost?Buffer.concat([buf,Buffer.from([253])]):buf);};
Bot.prototype.disconnect=function(){this._manualDisconnect=true;clearTimeout(this._reconnectTimer);clearTimeout(this._movementTimer);clearInterval(this._pingTimer);if(this.ws){try{this.ws.close();}catch(_){}}this.haveSnakeID=false;};
Bot.prototype.onOpen=function(){if(this.botManager&&this.botManager.getConnectedCount()>=this.botManager.botCount){this.disconnect();return;}this.hasConnected=true;this.send(Buffer.from([99]));if(this.botManager){this.botManager.setConnectedCount(this.botManager.getConnectedCount()+1);this.botManager.sendCountUpdate();}if(this.persistentBoost)this.boostSpeed(true);};
Bot.prototype.onClose=function(){clearTimeout(this._movementTimer);clearInterval(this._pingTimer);if(this.hasConnected&&this.botManager){this.hasConnected=false;this.botManager.setConnectedCount(this.botManager.getConnectedCount()-1);this.botManager.sendCountUpdate();}this.haveSnakeID=false;if(!this._manualDisconnect&&this.botManager&&this.botManager.isRunning()){clearTimeout(this._reconnectTimer);this._reconnectTimer=setTimeout(()=>{this._reconnectTimer=null;this.connect();},1500+Math.random()*1500);}};
Bot.prototype.onError=function(err){if(err&&process.env.DEBUG==='1')console.error(`[Bot ${this.id}]`,err.message);};
Bot.prototype.decodeSecrect=function(secret){const out=new Uint8Array(24);let state=0;for(let i=0;i<24;i++){let a=secret[17+i*2];if(a<=96)a+=32;a=(a-98-i*34)%26;if(a<0)a+=26;let b=secret[18+i*2];if(b<=96)b+=32;b=(b-115-i*34)%26;if(b<0)b+=26;let v=(a<<4)|b;const base=v>=97?97:65;v-=base;if(i===0)state=2+v;out[i]=((v+state)%26)+base;state+=3+v;}return out;};
Bot.prototype.boostSpeed=function(v){this.isBoost=!!v;this.send(Buffer.from([this.isBoost?253:254]));};
Bot.prototype.onMessage=function(data){const b=Buffer.from(data);if(b.length<3)return;const type=String.fromCharCode(b[2]);if(type==='6'){this.send(this.decodeSecrect(b));this.spawn();}else if(type==='p'){this.needPing=true;}else if(type==='a'){clearTimeout(this._movementTimer);const loop=()=>{if(!this.botManager||!this.botManager.isRunning())return;const t=this.botManager.getMovementTarget();this.moveTo(t.x,t.y);this._movementTimer=setTimeout(loop,180);};loop();clearInterval(this._pingTimer);this._pingTimer=setInterval(()=>this.send(Buffer.from([251])),150);}else if(type==='v'){this.disconnect();}else if((type==='g'||type==='n')&&b.length>=9){const id=b.readUInt16BE(3);if(id===this.snakeID){this.snakeX=b.readUInt16BE(5);this.snakeY=b.readUInt16BE(7);}}else if((type==='G'||type==='N')&&b.length>=7){const id=b.readUInt16BE(3);if(id===this.snakeID&&this.snakeX&&this.snakeY){this.snakeX+=b[5]-128;this.snakeY+=b[6]-128;}}else if(type==='s'&&!this.haveSnakeID&&b.length>=5){this.snakeID=b.readUInt16BE(3);this.haveSnakeID=true;if(b.length>=24){this.snakeX=((b[18]<<16)|(b[19]<<8)|b[20])/5;this.snakeY=((b[21]<<16)|(b[22]<<8)|b[23])/5;}}};
module.exports=Bot;
