'use strict';
const Bot=require('./Bot');
function numberEnv(name,fallback,min,max){const n=Number(process.env[name]);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.floor(n))):fallback;}
class BotManager{
 constructor(){this._0x2a7c=[];this._0x5f8e=process.env.GAME_SERVER||'';this._0x1d3b=process.env.GAME_ORIGIN||'https://slither.io';this._0x4c6f=null;this._0x8a2e=null;this._0x3e1a=0;this._0x9f2c=numberEnv('MAX_BOTS',100,1,1000);this.spawnDelay=numberEnv('SPAWN_DELAY_MS',250,50,5000);this._0xtornadoSettings={size:2000,separation:800,finalAng:90,rOC:.5,rotationDir:1};this._0x5b7c=11;this._0x9d1e=12;this._0xboostState=false;this._0xbotInterval=null;this.running=false;this.mode='follow';this.targetName='';this.targetXPos=null;this.targetYPos=null;}
 setServer(server,origin){this._0x5f8e=String(server||'').trim();if(origin)this._0x1d3b=String(origin).trim();}
 start(){this.stopBots();if(!this._0x5f8e)throw new Error('No game server configured');this.running=true;let id=0;const spawn=()=>{if(!this.running||id>=this._0x9f2c){clearInterval(this._0xbotInterval);this._0xbotInterval=null;return;}const bot=new Bot(++id);Object.assign(bot,{server:this._0x5f8e,serverInput:this._0x5f8e,origin:this._0x1d3b,proxies:[],Proxies:[],botManager:this,cosmetic:this._0x5b7c,tag:this._0x9d1e});bot.setMode(this.mode);bot.boostSpeed(this._0xboostState);bot.setTornadoSettings(this._0xtornadoSettings);if(this.targetXPos!==null&&this.targetYPos!==null)bot.setTarget(this.targetXPos,this.targetYPos);this._0x2a7c.push(bot);try{bot.connect();}catch(e){console.error(`[Bot ${id}] ${e.message}`);}this.logStatus();};spawn();this._0xbotInterval=setInterval(spawn,this.spawnDelay);}
 stopBots(){this.running=false;if(this._0xbotInterval)clearInterval(this._0xbotInterval);this._0xbotInterval=null;for(const bot of this._0x2a7c)try{bot.disconnect();}catch(_){}this._0x2a7c=[];this._0x3e1a=0;this.logStatus();}
 stop(){this.stopBots();}isRunning(){return this.running;}getMode(){return this.mode;}
 setMode(mode){const m=String(mode||'').toLowerCase();if(!['follow','wander','tornado','spiral','headhunter','focus','stop'].includes(m))throw new Error(`Invalid mode: ${m}`);this.mode=m;for(const bot of this._0x2a7c)bot.setMode(m);if(m==='stop')this.stopBots();return m;}
 setTarget(name,x,y){this.targetName=String(name||'').trim();if(Number.isFinite(Number(x))&&Number.isFinite(Number(y))){this.targetXPos=Number(x);this.targetYPos=Number(y);for(const bot of this._0x2a7c)bot.setTarget(this.targetXPos,this.targetYPos);}}
 updateTarget(x,y,name){this.setTarget(name||this.targetName,x,y);}clearTarget(){this.targetName='';this.targetXPos=null;this.targetYPos=null;for(const bot of this._0x2a7c)bot.setTarget(null,null);}
 updatePosition(x,y){const nx=Number(x),ny=Number(y);if(Number.isFinite(nx)&&Number.isFinite(ny)){this._0x4c6f=nx;this._0x8a2e=ny;}}
 getMovementTarget(){if((this.mode==='headhunter'||this.mode==='focus')&&Number.isFinite(this.targetXPos)&&Number.isFinite(this.targetYPos))return{x:this.targetXPos,y:this.targetYPos};return{x:this._0x4c6f,y:this._0x8a2e};}
 setBoostState(v){this._0xboostState=!!v;for(const b of this._0x2a7c)b.boostSpeed(this._0xboostState);}setCosmetic(v){this._0x5b7c=Number(v)||11;for(const b of this._0x2a7c)b.cosmetic=this._0x5b7c;}setTag(v){this._0x9d1e=Number(v)||12;for(const b of this._0x2a7c)b.tag=this._0x9d1e;}
 setTornadoSettings(s){this._0xtornadoSettings={...this._0xtornadoSettings,...(s||{})};for(const b of this._0x2a7c)b.setTornadoSettings(this._0xtornadoSettings);}
 setConnectedCount(n){this._0x3e1a=Math.max(0,Number(n)||0);}getConnectedCount(){return this._0x3e1a;}
 _0x8c7f(){this.start();}_0xstopAllBots(){this.stopBots();}_0xsetBoostState(v){this.setBoostState(v);}_0x4f2a(s){this.setTornadoSettings(s);}_0x3f8b(v){this.setCosmetic(v);}_0x7a9c(v){this.setTag(v);}_0x9c2d(){this.setMode('wander');}_0x3d8f(){this.setMode('tornado');}_0xToggleFixedCircle(){this.setMode('spiral');}_0x4e8f(){return this._0x5b7c;}_0x9b2a(){return this._0x9d1e;}
 getStatus(){const bots=this._0x2a7c.map(b=>({id:b.id,name:b.name||`Brunex Bot #${String(b.id).padStart(3,'0')}`,state:b.getState?b.getState():(b.hasConnected?'connected':'connecting'),snakeId:b.snakeID,autoTargetId:b.autoTargetId??null,visibleSnakes:b.snakes?.size||0,attempts:b.attempt||0,lastUrl:b.lastUrl||'',lastError:b.lastError||'',lastClose:b.lastClose||'',lastHttpStatus:b.lastHttpStatus??null,lastEvent:b.lastEvent||'',lastPacketType:b.lastPacketType||'',lastPacketLength:b.lastPacketLength||0,serverProtocolVersion:b.serverProtocolVersion??null}));return{service:'BrunexBots',ok:true,running:this.running,server:this._0x5f8e,origin:this._0x1d3b,mode:this.mode,connected:this._0x3e1a,joined:bots.filter(b=>b.state==='joined').length,connecting:bots.filter(b=>b.state==='connecting').length,reconnecting:bots.filter(b=>b.state==='reconnecting').length,verified:bots.filter(b=>b.state==='verified').length,dead:bots.filter(b=>b.state==='dead').length,maxBots:this._0x9f2c,target:this.targetName||'',bots};}
 logStatus(){if(process.env.STATUS_LOG!=='0')console.log(`[BrunexBots] joined=${this._0x2a7c.filter(b=>b.joined).length} connected=${this._0x3e1a}/${this._0x2a7c.length} mode=${this.mode}`);}sendCountUpdate(){this.logStatus();}get botCount(){return this._0x9f2c;}get xPos(){return this._0x4c6f;}get yPos(){return this._0x8a2e;}
}
module.exports=BotManager;
