'use strict';
const http=require('http');const WebSocket=require('ws');const BotManager=require('./src/BotManager');
const PORT=Number.parseInt(process.env.CONTROL_PORT||'8420',10);const HOST=process.env.CONTROL_HOST||'0.0.0.0';const manager=new BotManager();
const state=()=>manager.getStatus();const json=(res,code,value)=>{res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value));};
const httpServer=http.createServer((req,res)=>{if(req.url==='/'||req.url==='/health'||req.url==='/status')return json(res,200,state());res.writeHead(404);res.end('Not found');});
const wss=new WebSocket.Server({noServer:true,maxPayload:16384});const clients=new Set();const broadcast=msg=>{const text=JSON.stringify(msg);for(const ws of clients)if(ws.readyState===WebSocket.OPEN)ws.send(text);};
function originFor(msg){return typeof msg.origin==='string'&&/^https:\/\//i.test(msg.origin)?msg.origin:'https://slither.io';}
wss.on('connection',(ws,request)=>{clients.add(ws);console.log(`[Controller] control client connected from ${request.socket.remoteAddress||'unknown'}`);ws.send(JSON.stringify({type:'state',...state()}));ws.on('message',raw=>{let msg;try{msg=JSON.parse(raw.toString());}catch(_){return ws.send(JSON.stringify({type:'error',message:'Invalid JSON'}));}try{console.log(`[Controller] command: ${msg.type}`);
if(msg.type==='start'){if(typeof msg.server!=='string'||!msg.server.trim())throw new Error('Missing server');manager.setServer(msg.server.trim(),originFor(msg));manager.start();}
else if(msg.type==='stop')manager.stop();else if(msg.type==='movement')manager.updatePosition(msg.x,msg.y);
else if(msg.type==='world')manager.updateWorld(msg.world);else if(msg.type==='mode')manager.setMode(msg.mode);else if(msg.type==='target')manager.setTarget(msg.name,msg.x,msg.y);else if(msg.type==='clearTarget')manager.clearTarget();else if(msg.type==='boost')manager.setBoostState(msg.enabled);else if(msg.type==='tornadoSettings')manager.setTornadoSettings(msg.settings);else if(msg.type==='cosmetic')manager.setCosmetic(msg.value);else if(msg.type==='tag')manager.setTag(msg.value);else if(msg.type==='status')return ws.send(JSON.stringify({type:'status',...state()}));else return ws.send(JSON.stringify({type:'error',message:`Unknown command: ${msg.type}`}));
broadcast({type:'state',...state()});}catch(e){console.error(`[Controller] ${msg.type||'unknown'} failed: ${e.message}`);ws.send(JSON.stringify({type:'error',message:e.message}));}});ws.on('close',()=>{clients.delete(ws);console.log('[Controller] control client disconnected');});});
httpServer.on('upgrade',(request,socket,head)=>{if(request.url==='/control')return wss.handleUpgrade(request,socket,head,ws=>wss.emit('connection',ws,request));socket.destroy();});
httpServer.listen(PORT,HOST,()=>{console.log(`BrunexBots controller listening on ${HOST}:${PORT}`);console.log('Control endpoint: /control');console.log(`Status: http://127.0.0.1:${PORT}/status`);console.log(`Max bots: ${manager.botCount}`);});
setInterval(()=>broadcast({type:'state',...state()}),3000).unref();
function shutdown(){manager.stop();for(const ws of clients){try{ws.close();}catch(_){}}httpServer.close(()=>process.exit(0));setTimeout(()=>process.exit(0),3000).unref();}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
